#!/bin/sh

gumboot() {
	if ! [ -f /boot/gumboot/gumboot.lst ]; then
		# huh, weirdo's probably not using Gumboot
		# at least give em a warning
		printf "\033[1;33m===> WARNING: \033[0mGumboot not detected, but new kernel file path added.\n"
		printf "\033[1;33m===> WARNING: \033[0mUnable to automatically update config file.\n"
		exit 0
	fi
	update-gumboot
}

post_install() {
	gumboot
}

post_upgrade() {
	gumboot
}
